package com.situ.crm.dao;

import com.situ.crm.pojo.CustomerReprieve;
import com.situ.crm.pojo.CustomerReprieveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerReprieveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_reprieve
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    int countByExample(CustomerReprieveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_reprieve
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    int deleteByExample(CustomerReprieveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_reprieve
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_reprieve
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    int insert(CustomerReprieve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_reprieve
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    int insertSelective(CustomerReprieve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_reprieve
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    List<CustomerReprieve> selectByExample(CustomerReprieveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_reprieve
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    CustomerReprieve selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_reprieve
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") CustomerReprieve record, @Param("example") CustomerReprieveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_reprieve
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    int updateByExample(@Param("record") CustomerReprieve record, @Param("example") CustomerReprieveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_reprieve
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    int updateByPrimaryKeySelective(CustomerReprieve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_reprieve
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    int updateByPrimaryKey(CustomerReprieve record);
}