package com.situ.crm.dao;

import com.situ.crm.pojo.CustomerContact;
import com.situ.crm.pojo.CustomerContactExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    int countByExample(CustomerContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    int deleteByExample(CustomerContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    int insert(CustomerContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    int insertSelective(CustomerContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    List<CustomerContact> selectByExample(CustomerContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    CustomerContact selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") CustomerContact record, @Param("example") CustomerContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    int updateByExample(@Param("record") CustomerContact record, @Param("example") CustomerContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    int updateByPrimaryKeySelective(CustomerContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contact
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    int updateByPrimaryKey(CustomerContact record);
}