package com.situ.crm.dao;

import com.situ.crm.pojo.OrderDetails;
import com.situ.crm.pojo.OrderDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    int countByExample(OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    int deleteByExample(OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    int insert(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    int insertSelective(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    List<OrderDetails> selectByExample(OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    OrderDetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrderDetails record, @Param("example") OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    int updateByExample(@Param("record") OrderDetails record, @Param("example") OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    int updateByPrimaryKeySelective(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    int updateByPrimaryKey(OrderDetails record);
}