package com.situ.crm.pojo;

import java.util.Date;

public class CustomerService {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service.id
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service.serve_type
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String serveType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service.overview
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String overview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service.customer
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String customer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service.state
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service.service_request
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String serviceRequest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service.create_people
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String createPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service.create_time
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service.assigner
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String assigner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service.assign_time
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private Date assignTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service.service_proce
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String serviceProce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service.service_proce_people
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String serviceProcePeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service.service_proce_time
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private Date serviceProceTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service.service_proce_result
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String serviceProceResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_service.myd
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String myd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service.id
     *
     * @return the value of customer_service.id
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service.id
     *
     * @param id the value for customer_service.id
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service.serve_type
     *
     * @return the value of customer_service.serve_type
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getServeType() {
        return serveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service.serve_type
     *
     * @param serveType the value for customer_service.serve_type
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setServeType(String serveType) {
        this.serveType = serveType == null ? null : serveType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service.overview
     *
     * @return the value of customer_service.overview
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getOverview() {
        return overview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service.overview
     *
     * @param overview the value for customer_service.overview
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setOverview(String overview) {
        this.overview = overview == null ? null : overview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service.customer
     *
     * @return the value of customer_service.customer
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service.customer
     *
     * @param customer the value for customer_service.customer
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setCustomer(String customer) {
        this.customer = customer == null ? null : customer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service.state
     *
     * @return the value of customer_service.state
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service.state
     *
     * @param state the value for customer_service.state
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service.service_request
     *
     * @return the value of customer_service.service_request
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getServiceRequest() {
        return serviceRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service.service_request
     *
     * @param serviceRequest the value for customer_service.service_request
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setServiceRequest(String serviceRequest) {
        this.serviceRequest = serviceRequest == null ? null : serviceRequest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service.create_people
     *
     * @return the value of customer_service.create_people
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getCreatePeople() {
        return createPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service.create_people
     *
     * @param createPeople the value for customer_service.create_people
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setCreatePeople(String createPeople) {
        this.createPeople = createPeople == null ? null : createPeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service.create_time
     *
     * @return the value of customer_service.create_time
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service.create_time
     *
     * @param createTime the value for customer_service.create_time
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service.assigner
     *
     * @return the value of customer_service.assigner
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getAssigner() {
        return assigner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service.assigner
     *
     * @param assigner the value for customer_service.assigner
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setAssigner(String assigner) {
        this.assigner = assigner == null ? null : assigner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service.assign_time
     *
     * @return the value of customer_service.assign_time
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public Date getAssignTime() {
        return assignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service.assign_time
     *
     * @param assignTime the value for customer_service.assign_time
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setAssignTime(Date assignTime) {
        this.assignTime = assignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service.service_proce
     *
     * @return the value of customer_service.service_proce
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getServiceProce() {
        return serviceProce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service.service_proce
     *
     * @param serviceProce the value for customer_service.service_proce
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setServiceProce(String serviceProce) {
        this.serviceProce = serviceProce == null ? null : serviceProce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service.service_proce_people
     *
     * @return the value of customer_service.service_proce_people
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getServiceProcePeople() {
        return serviceProcePeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service.service_proce_people
     *
     * @param serviceProcePeople the value for customer_service.service_proce_people
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setServiceProcePeople(String serviceProcePeople) {
        this.serviceProcePeople = serviceProcePeople == null ? null : serviceProcePeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service.service_proce_time
     *
     * @return the value of customer_service.service_proce_time
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public Date getServiceProceTime() {
        return serviceProceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service.service_proce_time
     *
     * @param serviceProceTime the value for customer_service.service_proce_time
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setServiceProceTime(Date serviceProceTime) {
        this.serviceProceTime = serviceProceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service.service_proce_result
     *
     * @return the value of customer_service.service_proce_result
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getServiceProceResult() {
        return serviceProceResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service.service_proce_result
     *
     * @param serviceProceResult the value for customer_service.service_proce_result
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setServiceProceResult(String serviceProceResult) {
        this.serviceProceResult = serviceProceResult == null ? null : serviceProceResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_service.myd
     *
     * @return the value of customer_service.myd
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getMyd() {
        return myd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_service.myd
     *
     * @param myd the value for customer_service.myd
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setMyd(String myd) {
        this.myd = myd == null ? null : myd.trim();
    }
}