package com.situ.crm.pojo;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.num
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.name
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.region
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.manager_name
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String managerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.level
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.satisfy
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String satisfy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.credit
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.address
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.post_code
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.phone
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.fax
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.web_site
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String webSite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.licence_no
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String licenceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.legal_person
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String legalPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.bankroll
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String bankroll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.turnover
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String turnover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.bank_name
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.bank_account
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.local_tax_no
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String localTaxNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.national_tax_no
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String nationalTaxNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.status
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.num
     *
     * @return the value of customer.num
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.num
     *
     * @param num the value for customer.num
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.name
     *
     * @return the value of customer.name
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.name
     *
     * @param name the value for customer.name
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.region
     *
     * @return the value of customer.region
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.region
     *
     * @param region the value for customer.region
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.manager_name
     *
     * @return the value of customer.manager_name
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.manager_name
     *
     * @param managerName the value for customer.manager_name
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.level
     *
     * @return the value of customer.level
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.level
     *
     * @param level the value for customer.level
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.satisfy
     *
     * @return the value of customer.satisfy
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getSatisfy() {
        return satisfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.satisfy
     *
     * @param satisfy the value for customer.satisfy
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setSatisfy(String satisfy) {
        this.satisfy = satisfy == null ? null : satisfy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.credit
     *
     * @return the value of customer.credit
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.credit
     *
     * @param credit the value for customer.credit
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setCredit(String credit) {
        this.credit = credit == null ? null : credit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.address
     *
     * @return the value of customer.address
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.address
     *
     * @param address the value for customer.address
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.post_code
     *
     * @return the value of customer.post_code
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.post_code
     *
     * @param postCode the value for customer.post_code
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.phone
     *
     * @return the value of customer.phone
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.phone
     *
     * @param phone the value for customer.phone
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.fax
     *
     * @return the value of customer.fax
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.fax
     *
     * @param fax the value for customer.fax
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.web_site
     *
     * @return the value of customer.web_site
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getWebSite() {
        return webSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.web_site
     *
     * @param webSite the value for customer.web_site
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setWebSite(String webSite) {
        this.webSite = webSite == null ? null : webSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.licence_no
     *
     * @return the value of customer.licence_no
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getLicenceNo() {
        return licenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.licence_no
     *
     * @param licenceNo the value for customer.licence_no
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setLicenceNo(String licenceNo) {
        this.licenceNo = licenceNo == null ? null : licenceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.legal_person
     *
     * @return the value of customer.legal_person
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.legal_person
     *
     * @param legalPerson the value for customer.legal_person
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson == null ? null : legalPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.bankroll
     *
     * @return the value of customer.bankroll
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getBankroll() {
        return bankroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.bankroll
     *
     * @param bankroll the value for customer.bankroll
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setBankroll(String bankroll) {
        this.bankroll = bankroll == null ? null : bankroll.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.turnover
     *
     * @return the value of customer.turnover
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getTurnover() {
        return turnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.turnover
     *
     * @param turnover the value for customer.turnover
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setTurnover(String turnover) {
        this.turnover = turnover == null ? null : turnover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.bank_name
     *
     * @return the value of customer.bank_name
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.bank_name
     *
     * @param bankName the value for customer.bank_name
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.bank_account
     *
     * @return the value of customer.bank_account
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.bank_account
     *
     * @param bankAccount the value for customer.bank_account
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.local_tax_no
     *
     * @return the value of customer.local_tax_no
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getLocalTaxNo() {
        return localTaxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.local_tax_no
     *
     * @param localTaxNo the value for customer.local_tax_no
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setLocalTaxNo(String localTaxNo) {
        this.localTaxNo = localTaxNo == null ? null : localTaxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.national_tax_no
     *
     * @return the value of customer.national_tax_no
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getNationalTaxNo() {
        return nationalTaxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.national_tax_no
     *
     * @param nationalTaxNo the value for customer.national_tax_no
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setNationalTaxNo(String nationalTaxNo) {
        this.nationalTaxNo = nationalTaxNo == null ? null : nationalTaxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.status
     *
     * @return the value of customer.status
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.status
     *
     * @param status the value for customer.status
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}