package com.situ.crm.pojo;

public class CustomerReprieve {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_reprieve.id
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_reprieve.loss_id
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private Integer lossId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_reprieve.measure
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String measure;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_reprieve.id
     *
     * @return the value of customer_reprieve.id
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_reprieve.id
     *
     * @param id the value for customer_reprieve.id
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_reprieve.loss_id
     *
     * @return the value of customer_reprieve.loss_id
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public Integer getLossId() {
        return lossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_reprieve.loss_id
     *
     * @param lossId the value for customer_reprieve.loss_id
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setLossId(Integer lossId) {
        this.lossId = lossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_reprieve.measure
     *
     * @return the value of customer_reprieve.measure
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getMeasure() {
        return measure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_reprieve.measure
     *
     * @param measure the value for customer_reprieve.measure
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setMeasure(String measure) {
        this.measure = measure == null ? null : measure.trim();
    }
}