package com.situ.crm.pojo;

import java.util.Date;

public class CustomerOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_order.id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_order.customer_id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_order.order_no
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_order.order_date
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_order.address
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_order.status
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_order.id
     *
     * @return the value of customer_order.id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_order.id
     *
     * @param id the value for customer_order.id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_order.customer_id
     *
     * @return the value of customer_order.customer_id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_order.customer_id
     *
     * @param customerId the value for customer_order.customer_id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_order.order_no
     *
     * @return the value of customer_order.order_no
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_order.order_no
     *
     * @param orderNo the value for customer_order.order_no
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_order.order_date
     *
     * @return the value of customer_order.order_date
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_order.order_date
     *
     * @param orderDate the value for customer_order.order_date
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_order.address
     *
     * @return the value of customer_order.address
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_order.address
     *
     * @param address the value for customer_order.address
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_order.status
     *
     * @return the value of customer_order.status
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_order.status
     *
     * @param status the value for customer_order.status
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}