package com.situ.crm.pojo;

public class CustomerLossMeasure {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_loss_measure.id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_loss_measure.loss_id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private Integer lossId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_loss_measure.measure
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String measure;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_loss_measure.id
     *
     * @return the value of customer_loss_measure.id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_loss_measure.id
     *
     * @param id the value for customer_loss_measure.id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_loss_measure.loss_id
     *
     * @return the value of customer_loss_measure.loss_id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public Integer getLossId() {
        return lossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_loss_measure.loss_id
     *
     * @param lossId the value for customer_loss_measure.loss_id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setLossId(Integer lossId) {
        this.lossId = lossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_loss_measure.measure
     *
     * @return the value of customer_loss_measure.measure
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getMeasure() {
        return measure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_loss_measure.measure
     *
     * @param measure the value for customer_loss_measure.measure
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setMeasure(String measure) {
        this.measure = measure == null ? null : measure.trim();
    }
}