package com.situ.crm.pojo;

import java.util.Date;

public class CustomerLoss {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_loss.id
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_loss.cus_no
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String cusNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_loss.cus_name
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String cusName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_loss.cus_manager
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String cusManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_loss.last_order_time
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private Date lastOrderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_loss.confirm_loss_time
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private Date confirmLossTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_loss.state
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_loss.loss_reason
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String lossReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_loss.id
     *
     * @return the value of customer_loss.id
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_loss.id
     *
     * @param id the value for customer_loss.id
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_loss.cus_no
     *
     * @return the value of customer_loss.cus_no
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getCusNo() {
        return cusNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_loss.cus_no
     *
     * @param cusNo the value for customer_loss.cus_no
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setCusNo(String cusNo) {
        this.cusNo = cusNo == null ? null : cusNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_loss.cus_name
     *
     * @return the value of customer_loss.cus_name
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getCusName() {
        return cusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_loss.cus_name
     *
     * @param cusName the value for customer_loss.cus_name
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setCusName(String cusName) {
        this.cusName = cusName == null ? null : cusName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_loss.cus_manager
     *
     * @return the value of customer_loss.cus_manager
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getCusManager() {
        return cusManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_loss.cus_manager
     *
     * @param cusManager the value for customer_loss.cus_manager
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setCusManager(String cusManager) {
        this.cusManager = cusManager == null ? null : cusManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_loss.last_order_time
     *
     * @return the value of customer_loss.last_order_time
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public Date getLastOrderTime() {
        return lastOrderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_loss.last_order_time
     *
     * @param lastOrderTime the value for customer_loss.last_order_time
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setLastOrderTime(Date lastOrderTime) {
        this.lastOrderTime = lastOrderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_loss.confirm_loss_time
     *
     * @return the value of customer_loss.confirm_loss_time
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public Date getConfirmLossTime() {
        return confirmLossTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_loss.confirm_loss_time
     *
     * @param confirmLossTime the value for customer_loss.confirm_loss_time
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setConfirmLossTime(Date confirmLossTime) {
        this.confirmLossTime = confirmLossTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_loss.state
     *
     * @return the value of customer_loss.state
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_loss.state
     *
     * @param state the value for customer_loss.state
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_loss.loss_reason
     *
     * @return the value of customer_loss.loss_reason
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getLossReason() {
        return lossReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_loss.loss_reason
     *
     * @param lossReason the value for customer_loss.loss_reason
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setLossReason(String lossReason) {
        this.lossReason = lossReason == null ? null : lossReason.trim();
    }
}