package com.situ.crm.pojo;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.khno
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String khno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.name
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.area
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cus_manager
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String cusManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.level
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.myd
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String myd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.xyd
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String xyd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.address
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.post_code
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.phone
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.fax
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.web_site
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String webSite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.yyzzzch
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String yyzzzch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.fr
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String fr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.zczj
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String zczj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.nyye
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String nyye;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.khyh
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String khyh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.khzh
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String khzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.dsdjh
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String dsdjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.gsdjh
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private String gsdjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.state
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.khno
     *
     * @return the value of customer.khno
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getKhno() {
        return khno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.khno
     *
     * @param khno the value for customer.khno
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setKhno(String khno) {
        this.khno = khno == null ? null : khno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.name
     *
     * @return the value of customer.name
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.name
     *
     * @param name the value for customer.name
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.area
     *
     * @return the value of customer.area
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.area
     *
     * @param area the value for customer.area
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cus_manager
     *
     * @return the value of customer.cus_manager
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getCusManager() {
        return cusManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cus_manager
     *
     * @param cusManager the value for customer.cus_manager
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setCusManager(String cusManager) {
        this.cusManager = cusManager == null ? null : cusManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.level
     *
     * @return the value of customer.level
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.level
     *
     * @param level the value for customer.level
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.myd
     *
     * @return the value of customer.myd
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getMyd() {
        return myd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.myd
     *
     * @param myd the value for customer.myd
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setMyd(String myd) {
        this.myd = myd == null ? null : myd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.xyd
     *
     * @return the value of customer.xyd
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getXyd() {
        return xyd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.xyd
     *
     * @param xyd the value for customer.xyd
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setXyd(String xyd) {
        this.xyd = xyd == null ? null : xyd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.address
     *
     * @return the value of customer.address
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.address
     *
     * @param address the value for customer.address
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.post_code
     *
     * @return the value of customer.post_code
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.post_code
     *
     * @param postCode the value for customer.post_code
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.phone
     *
     * @return the value of customer.phone
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.phone
     *
     * @param phone the value for customer.phone
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.fax
     *
     * @return the value of customer.fax
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.fax
     *
     * @param fax the value for customer.fax
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.web_site
     *
     * @return the value of customer.web_site
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getWebSite() {
        return webSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.web_site
     *
     * @param webSite the value for customer.web_site
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setWebSite(String webSite) {
        this.webSite = webSite == null ? null : webSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.yyzzzch
     *
     * @return the value of customer.yyzzzch
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getYyzzzch() {
        return yyzzzch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.yyzzzch
     *
     * @param yyzzzch the value for customer.yyzzzch
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setYyzzzch(String yyzzzch) {
        this.yyzzzch = yyzzzch == null ? null : yyzzzch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.fr
     *
     * @return the value of customer.fr
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getFr() {
        return fr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.fr
     *
     * @param fr the value for customer.fr
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setFr(String fr) {
        this.fr = fr == null ? null : fr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.zczj
     *
     * @return the value of customer.zczj
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getZczj() {
        return zczj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.zczj
     *
     * @param zczj the value for customer.zczj
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setZczj(String zczj) {
        this.zczj = zczj == null ? null : zczj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.nyye
     *
     * @return the value of customer.nyye
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getNyye() {
        return nyye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.nyye
     *
     * @param nyye the value for customer.nyye
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setNyye(String nyye) {
        this.nyye = nyye == null ? null : nyye.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.khyh
     *
     * @return the value of customer.khyh
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getKhyh() {
        return khyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.khyh
     *
     * @param khyh the value for customer.khyh
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setKhyh(String khyh) {
        this.khyh = khyh == null ? null : khyh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.khzh
     *
     * @return the value of customer.khzh
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getKhzh() {
        return khzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.khzh
     *
     * @param khzh the value for customer.khzh
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setKhzh(String khzh) {
        this.khzh = khzh == null ? null : khzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.dsdjh
     *
     * @return the value of customer.dsdjh
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getDsdjh() {
        return dsdjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.dsdjh
     *
     * @param dsdjh the value for customer.dsdjh
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setDsdjh(String dsdjh) {
        this.dsdjh = dsdjh == null ? null : dsdjh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.gsdjh
     *
     * @return the value of customer.gsdjh
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public String getGsdjh() {
        return gsdjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.gsdjh
     *
     * @param gsdjh the value for customer.gsdjh
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setGsdjh(String gsdjh) {
        this.gsdjh = gsdjh == null ? null : gsdjh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.state
     *
     * @return the value of customer.state
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.state
     *
     * @param state the value for customer.state
     *
     * @mbggenerated Thu Oct 26 11:54:32 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }
}