package com.situ.crm.pojo;

public class OrderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.order_id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_name
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_num
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private Integer productNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.unit
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.price
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.sum
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    private Float sum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.id
     *
     * @return the value of order_item.id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.id
     *
     * @param id the value for order_item.id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.order_id
     *
     * @return the value of order_item.order_id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.order_id
     *
     * @param orderId the value for order_item.order_id
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_name
     *
     * @return the value of order_item.product_name
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_name
     *
     * @param productName the value for order_item.product_name
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_num
     *
     * @return the value of order_item.product_num
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public Integer getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_num
     *
     * @param productNum the value for order_item.product_num
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setProductNum(Integer productNum) {
        this.productNum = productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.unit
     *
     * @return the value of order_item.unit
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.unit
     *
     * @param unit the value for order_item.unit
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.price
     *
     * @return the value of order_item.price
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.price
     *
     * @param price the value for order_item.price
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.sum
     *
     * @return the value of order_item.sum
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public Float getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.sum
     *
     * @param sum the value for order_item.sum
     *
     * @mbggenerated Mon Oct 30 14:03:59 CST 2017
     */
    public void setSum(Float sum) {
        this.sum = sum;
    }
}